import type { Place } from "./types";

/**
 * Curated from the GeoNames cities5000 export (CC BY 4.0), snapshot 2026-07-29.
 * Precision is intentionally limited in the UI: coordinates are used only for
 * weather and sun calculations and are never displayed or shared.
 */
export const PLACES: readonly Place[] = [
  {
    id: "longyearbyen",
    geonameId: 2729907,
    name: "Longyearbyen",
    country: "Svalbard, Norwegen",
    latitude: 78.22334,
    longitude: 15.64689,
    timeZone: "Arctic/Longyearbyen",
    landscape: "arctic",
    sceneSeed: 7,
  },
  {
    id: "tromso",
    geonameId: 3133895,
    name: "Tromsø",
    country: "Norwegen",
    latitude: 69.6489,
    longitude: 18.95508,
    timeZone: "Europe/Oslo",
    landscape: "arctic",
    sceneSeed: 13,
  },
  {
    id: "reykjavik",
    geonameId: 3413829,
    name: "Reykjavík",
    country: "Island",
    latitude: 64.13548,
    longitude: -21.89541,
    timeZone: "Atlantic/Reykjavik",
    landscape: "coast",
    sceneSeed: 19,
  },
  {
    id: "torshavn",
    geonameId: 2611396,
    name: "Tórshavn",
    country: "Färöer",
    latitude: 62.00973,
    longitude: -6.77164,
    timeZone: "Atlantic/Faroe",
    landscape: "island",
    sceneSeed: 23,
  },
  {
    id: "nuuk",
    geonameId: 3421319,
    name: "Nuuk",
    country: "Grönland",
    latitude: 64.18347,
    longitude: -51.72157,
    timeZone: "America/Nuuk",
    landscape: "arctic",
    sceneSeed: 29,
  },
  {
    id: "anchorage",
    geonameId: 5879400,
    name: "Anchorage",
    country: "Alaska, USA",
    latitude: 61.21806,
    longitude: -149.90028,
    timeZone: "America/Anchorage",
    landscape: "hills",
    sceneSeed: 31,
  },
  {
    id: "whitehorse",
    geonameId: 6180550,
    name: "Whitehorse",
    country: "Kanada",
    latitude: 60.71611,
    longitude: -135.05375,
    timeZone: "America/Whitehorse",
    landscape: "hills",
    sceneSeed: 37,
  },
  {
    id: "vancouver",
    geonameId: 6173331,
    name: "Vancouver",
    country: "Kanada",
    latitude: 49.24966,
    longitude: -123.11934,
    timeZone: "America/Vancouver",
    landscape: "coast",
    sceneSeed: 41,
  },
  {
    id: "san-francisco",
    geonameId: 5391959,
    name: "San Francisco",
    country: "Kalifornien, USA",
    latitude: 37.77493,
    longitude: -122.41942,
    timeZone: "America/Los_Angeles",
    landscape: "coast",
    sceneSeed: 43,
  },
  {
    id: "mexico-city",
    geonameId: 3530597,
    name: "Mexiko-Stadt",
    country: "Mexiko",
    latitude: 19.42847,
    longitude: -99.12766,
    timeZone: "America/Mexico_City",
    landscape: "plateau",
    sceneSeed: 47,
  },
  {
    id: "quito",
    geonameId: 3652462,
    name: "Quito",
    country: "Ecuador",
    latitude: -0.22985,
    longitude: -78.52495,
    timeZone: "America/Guayaquil",
    landscape: "plateau",
    sceneSeed: 53,
  },
  {
    id: "ushuaia",
    geonameId: 3833367,
    name: "Ushuaia",
    country: "Argentinien",
    latitude: -54.81084,
    longitude: -68.31591,
    timeZone: "America/Argentina/Ushuaia",
    landscape: "coast",
    sceneSeed: 59,
  },
  {
    id: "hanga-roa",
    geonameId: 4030754,
    name: "Hanga Roa",
    country: "Rapa Nui, Chile",
    latitude: -27.15253,
    longitude: -109.42438,
    timeZone: "Pacific/Easter",
    landscape: "island",
    sceneSeed: 61,
  },
  {
    id: "ponta-delgada",
    geonameId: 6941014,
    name: "Ponta Delgada",
    country: "Azoren, Portugal",
    latitude: 37.73952,
    longitude: -25.66874,
    timeZone: "Atlantic/Azores",
    landscape: "island",
    sceneSeed: 67,
  },
  {
    id: "dakar",
    geonameId: 2253354,
    name: "Dakar",
    country: "Senegal",
    latitude: 14.6937,
    longitude: -17.44406,
    timeZone: "Africa/Dakar",
    landscape: "coast",
    sceneSeed: 71,
  },
  {
    id: "cape-town",
    geonameId: 3369157,
    name: "Kapstadt",
    country: "Südafrika",
    latitude: -33.92584,
    longitude: 18.42322,
    timeZone: "Africa/Johannesburg",
    landscape: "coast",
    sceneSeed: 73,
  },
  {
    id: "nairobi",
    geonameId: 184745,
    name: "Nairobi",
    country: "Kenia",
    latitude: -1.28333,
    longitude: 36.81667,
    timeZone: "Africa/Nairobi",
    landscape: "plateau",
    sceneSeed: 79,
  },
  {
    id: "cairo",
    geonameId: 360630,
    name: "Kairo",
    country: "Ägypten",
    latitude: 30.06263,
    longitude: 31.24967,
    timeZone: "Africa/Cairo",
    landscape: "city",
    sceneSeed: 83,
  },
  {
    id: "istanbul",
    geonameId: 745044,
    name: "Istanbul",
    country: "Türkei",
    latitude: 41.01384,
    longitude: 28.94966,
    timeZone: "Europe/Istanbul",
    landscape: "coast",
    sceneSeed: 89,
  },
  {
    id: "jaipur",
    geonameId: 1269515,
    name: "Jaipur",
    country: "Indien",
    latitude: 26.91962,
    longitude: 75.78781,
    timeZone: "Asia/Kolkata",
    landscape: "city",
    sceneSeed: 97,
  },
  {
    id: "kathmandu",
    geonameId: 1283240,
    name: "Kathmandu",
    country: "Nepal",
    latitude: 27.70169,
    longitude: 85.3206,
    timeZone: "Asia/Kathmandu",
    landscape: "hills",
    sceneSeed: 101,
  },
  {
    id: "thimphu",
    geonameId: 1252416,
    name: "Thimphu",
    country: "Bhutan",
    latitude: 27.46609,
    longitude: 89.64191,
    timeZone: "Asia/Thimphu",
    landscape: "hills",
    sceneSeed: 103,
  },
  {
    id: "singapore",
    geonameId: 1880252,
    name: "Singapur",
    country: "Singapur",
    latitude: 1.28967,
    longitude: 103.85007,
    timeZone: "Asia/Singapore",
    landscape: "city",
    sceneSeed: 107,
  },
  {
    id: "hanoi",
    geonameId: 1581130,
    name: "Hanoi",
    country: "Vietnam",
    latitude: 21.0245,
    longitude: 105.84117,
    timeZone: "Asia/Bangkok",
    landscape: "city",
    sceneSeed: 109,
  },
  {
    id: "seoul",
    geonameId: 1835848,
    name: "Seoul",
    country: "Südkorea",
    latitude: 37.566,
    longitude: 126.9784,
    timeZone: "Asia/Seoul",
    landscape: "city",
    sceneSeed: 113,
  },
  {
    id: "tokyo",
    geonameId: 1850147,
    name: "Tokio",
    country: "Japan",
    latitude: 35.6895,
    longitude: 139.69171,
    timeZone: "Asia/Tokyo",
    landscape: "city",
    sceneSeed: 127,
  },
  {
    id: "yakutsk",
    geonameId: 2013159,
    name: "Jakutsk",
    country: "Russland",
    latitude: 62.03114,
    longitude: 129.72288,
    timeZone: "Asia/Yakutsk",
    landscape: "hills",
    sceneSeed: 131,
  },
  {
    id: "ulaanbaatar",
    geonameId: 2028462,
    name: "Ulaanbaatar",
    country: "Mongolei",
    latitude: 47.90771,
    longitude: 106.88324,
    timeZone: "Asia/Ulaanbaatar",
    landscape: "plateau",
    sceneSeed: 137,
  },
  {
    id: "perth",
    geonameId: 2063523,
    name: "Perth",
    country: "Australien",
    latitude: -31.95224,
    longitude: 115.8614,
    timeZone: "Australia/Perth",
    landscape: "coast",
    sceneSeed: 139,
  },
  {
    id: "hobart",
    geonameId: 2163355,
    name: "Hobart",
    country: "Tasmanien, Australien",
    latitude: -42.87936,
    longitude: 147.32941,
    timeZone: "Australia/Hobart",
    landscape: "coast",
    sceneSeed: 149,
  },
  {
    id: "suva",
    geonameId: 2198148,
    name: "Suva",
    country: "Fidschi",
    latitude: -18.13683,
    longitude: 178.42531,
    timeZone: "Pacific/Fiji",
    landscape: "island",
    sceneSeed: 151,
  },
  {
    id: "apia",
    geonameId: 4035413,
    name: "Apia",
    country: "Samoa",
    latitude: -13.83333,
    longitude: -171.76666,
    timeZone: "Pacific/Apia",
    landscape: "island",
    sceneSeed: 157,
  },
  {
    id: "waitangi",
    geonameId: 4032804,
    name: "Waitangi",
    country: "Chathaminseln, Neuseeland",
    latitude: -43.95353,
    longitude: -176.55973,
    timeZone: "Pacific/Chatham",
    landscape: "island",
    sceneSeed: 163,
  },
] as const;

export function chooseNextPlace(
  currentId: string | null,
  random: () => number = Math.random,
): Place {
  const candidates = PLACES.filter((place) => place.id !== currentId);
  const index = Math.min(candidates.length - 1, Math.floor(random() * candidates.length));
  const place = candidates[index];
  if (!place) {
    throw new Error("Kein Ort verfügbar.");
  }
  return place;
}

export function getPlaceById(id: string | null): Place | null {
  if (!id) return null;
  return PLACES.find((place) => place.id === id) ?? null;
}
